add method to controller. add default constructor to Contact.class
Isse:
http://localhost:8080/hello/contacts?nameFilter=^A.*$
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986